Fix color reunion
IGNF/ign-pdal-tools pull request #45
Opened 2024-06-21 13:42 UTC by gliegard

- detect white images
- choose stream for RGB and IRC colorization
- version 1.6.0

2024-06-24 07:34 UTC, leavauchier requested changes

2024-06-24 07:34 UTC, leavauchier commented on pdaltools/color.py
> +    # return true if that all element have the value 255
si c'est un numpy array, pourquoi ne pas directement faire un `np.all(band3 == 255)` ? J'ai l'impression qu'il y a plus de chances d'avoir une lazy implementation et que ce soit plus rapide de façon générale

2024-06-24 07:34 UTC, leavauchier commented on pdaltools/color.py
> +    band3 = rasterArray[2]
pourquoi spécifiquement la 3e bande ? Ca donne quoi pour l'IRC dans ce cas ?

2024-06-24 07:34 UTC, leavauchier commented on pdaltools/color.py
> +        if check_images and is_image_white(tmp_ortho_irc.name):
pourquoi mettre ça 2 fois (une pour rgb et une pour irc) plutôt que directement dans `download_image_from_geoplateforme` ? (j'ai l'impression que le nom du stream peut suffire à donner l'info, sans avoir à rajouter RGB ou IRC dans le message d'erreur)

2024-06-24 07:34 UTC, leavauchier commented on script/test/test_color_fail_white_image.sh
> +echo
pourquoi ne pas faire ça avec pytest directement comme les autres tests ?

2024-06-24 07:34 UTC, leavauchier commented on test/test_color.py
> +    for dimension_index in [12, 13, 14]:  # 12, 13, 14 are RGB in this format
y a pas moyen de passer par les noms de dimensions plutôt que les indices ? Ca paraitrait plus robuste (mais en me^me temps pas sûre que ce soit nécessaire pour un test)

2024-06-24 07:34 UTC, leavauchier commented on test/test_color.py
> +    assert "Downloaded image is white" in str(excinfo.value)
problème d'indentation a priori, ça devrait être dans ton `with` vu que tu utilises excinfo

2024-06-24 16:01 UTC, gliegard commented on pdaltools/color.py
> +    # return true if that all element have the value 255
ok, j'ai modifé le code

2024-06-24 16:01 UTC, gliegard commented on pdaltools/color.py
> +    band3 = rasterArray[2]
bien vu, j'ai fait la modification

2024-06-24 16:02 UTC, gliegard commented on pdaltools/color.py
> +        if check_images and is_image_white(tmp_ortho_irc.name):
bonne idée, j'ai fait la modif

2024-06-24 16:04 UTC, gliegard commented on script/test/test_color_fail_white_image.sh
> +echo
c'était pour vérifier les passages de paramètre (parse args dans le main). J'ai pas de bon exemple pour tester ça, on peut en parler.

2024-06-24 16:07 UTC, gliegard commented on test/test_color.py
> +    assert "Downloaded image is white" in str(excinfo.value)
non là y'a pas de pb, dans la doc ils font comme ça.

2024-06-24 16:35 UTC, gliegard commented on test/test_color.py
> +    for dimension_index in [12, 13, 14]:  # 12, 13, 14 are RGB in this format
j'ai supprimer le bout de code

2024-06-25 07:04 UTC, leavauchier approved these changes

2024-06-25 07:04 UTC, leavauchier commented on pdaltools/color.py
> +    rasterArray = gdal_array.LoadFile(filename)
pinaillage en règle : `raster_array` au lieu de `rasterArray` pour respecter les conventions

2024-06-25 08:10 UTC, merged