Add points las
IGNF/ign-pdal-tools pull request #68
Opened 2024-10-18 16:05 UTC by alavenant

2024-11-04 11:10 UTC, gliegard requested changes

2024-11-04 11:10 UTC, gliegard commented on test/test_add_points_in_las.py
> +        geom.append(build_random_point())
la géométrie est d'abord constituée de points...

2024-11-04 11:10 UTC, gliegard commented on test/test_add_points_in_las.py
> +        geom.append(polygon)
... puis la geométrie est constituée de Polygones.. ça correspond à quoi concrètement ?

2024-11-04 11:10 UTC, gliegard commented on test/test_add_points_in_las.py
> +def test_extract_points_from_geo(execution_number):
ce test est compliqué (je vois pas à quoi ça correspond) et ça test finalement seulement le nombre de points ajoutés.

Je pensais à un test plus simple (dans un mini LAS, tu lui donne une geométrie élémentaire , genre un polygon simple ((0, 1) (1,0) (1, 1) (0, 0) et tu vérifies que tu as bien ces points dans le LAS , pas juste 4 points ajoutés , mais bien des points à ces coordonnées

2024-11-18 10:45 UTC, alavenant commented on test/test_add_points_in_las.py
> +        geom.append(build_random_point())
L'idée est de générer des géométries aléatoire (ponctuelle et polygone), et de générer plusieurs tests.

2024-11-18 15:26 UTC, alavenant commented on test/test_add_points_in_las.py
> +def test_extract_points_from_geo(execution_number):
Mais j'ai modifié les tests pour qu'ils soient plus simples

2024-11-18 15:29 UTC, alavenant commented on test/test_add_points_in_las.py
> +        geom.append(build_random_point())
Mais j'ai modifié pour que ce soit plus simple

2024-11-18 15:47 UTC, gliegard commented on test/test_add_points_in_las.py
> +    points_las = add_point_in_las(pt_geo, True)
pour la lisibilité devant `True`, faudrait mettre le nom du parametre
points_las = add_point_in_las(pt_geo=pt_geo, only_inside=True)

aussi, `only_inside` pourrait s'appeller `inside_las`

ou bien `inside_las` pourrait s'appeler `only_inside`

en tout cas, comme c'est le même concept, ça devrait avoir le même nom

2024-11-18 15:47 UTC, gliegard commented on test/test_add_points_in_las.py
> +    points_las = add_point_in_las(pt_geo, False)
pour la lisibilité devant `True`, faudrait mettre le nom du parametre

2024-11-18 15:47 UTC, gliegard commented on test/test_add_points_in_las.py
> +    points_las = add_point_in_las(pt_geo, True)
pour la lisibilité devant `True`, faudrait mettre le nom du parametre

2024-11-18 15:52 UTC, alavenant commented on test/test_add_points_in_las.py
> +    points_las = add_point_in_las(pt_geo, True)
done

2024-11-18 15:52 UTC, alavenant commented on test/test_add_points_in_las.py
> +    points_las = add_point_in_las(pt_geo, True)
done

2024-11-18 17:02 UTC, gliegard approved these changes

2024-11-22 16:12 UTC, merged