Fix standardisation on files from TerraSolid
IGNF/ign-pdal-tools pull request #8
Opened 2023-07-07 10:12 UTC by leavauchier

2023-07-10 09:54 UTC, gliegard approved these changes

2023-07-12 17:24 UTC, gliegard requested changes
As you move the Unlock part from the Color module, can you also :
- add a main to the Unlock module
- in the Color module, main function, remove the Unlock part

2023-07-17 07:41 UTC, leavauchier commented
> As you move the Unlock part from the Color module, can you also :
>    add a main to the Unlock module
>    in the Color module, main function, remove the Unlock part

This implies a change in the api, do you think it is worth it?

2023-07-17 11:50 UTC, gliegard approved these changes

2023-07-17 12:00 UTC, merged